### ISSUE TITLE
multiple windows

### ISSUE THREAD

**Issue by bigov** [janekb04/glfwpp#136] opened 2021-11-14 12:54 UTC
If you build several windows:
```cpp
#include <vector>
#include "include/glfwpp/glfwpp.h"
static void keyboard_callback(glfw::Window& W, glfw::KeyCode K, int, glfw::KeyState S, glfw::ModifierKeyBit)
{
  if(K == glfw::KeyCode::Escape && S == glfw::KeyState::Release) W.setShouldClose(true);
}

int main()
{
  std::vector<glfw::Window> DSE {};

  [[maybe_unused]]auto GLFW = glfw::init();

  DSE.emplace_back( 640, 480, "GLFWPP N_1" );
  DSE.back().keyEvent.setCallback(keyboard_callback);

  DSE.emplace_back( 640, 480, "GLFWPP N_2" );
  DSE.back().keyEvent.setCallback(keyboard_callback);

  DSE.emplace_back( 640, 480, "GLFWPP N_3" );
  DSE.back().keyEvent.setCallback(keyboard_callback);

  while (!DSE.empty())
  {
    for(auto& W: DSE)
    {
      glfw::makeContextCurrent(W);
      glfw::pollEvents();

      if(W.shouldClose())
      {
        auto it = std::find_if(DSE.begin(), DSE.end(), [&W](const auto& cW){ return cW == W; });
        if(it != DSE.end()) DSE.erase(it);
      }
    }
  }
}
```
then the event handler only connects to the latter. Maybe I'm doing wrong?

**Comment by janekb04** [comment] 2021-11-14 17:53
Hi @bigov, thanks for reporting this issue. I was able to find what is the problem. The `Window` class [move constructor and move assignment operators](https://github.com/janekb04/glfwpp/blob/d0951a0ff042789e8cfdcbe18e9ec38b4f6f5b16/include/glfwpp/window.h#L658) do not move event handlers, but instead, default-construct them. I am working on a fix.
You are using the library correctly, though the call to `glfw::pollEvents` should probably be outside the innermost loop. Generally, events are polled per-frame, rather than per-window and `pollEvents` polls all windows at once.

**Comment by janekb04** [comment] 2021-11-14 17:55
A temporary fix would be to call `DSE.reserve()` at the beginning, as the issue is caused by the `vector` reallocating memory and moving existing `Window` objects.

**Comment by janekb04** [comment] 2021-11-14 20:37
@bigov I opened PR #137. Could you verify that it solves your issue?

**Comment by bigov** [comment] 2021-11-15 01:13
unfortunately I cannot confirm. You can check it yourself. For example - "native code":
```cpp
#include <iostream>
#include <vector>
#include "include/GLFW/glfw3.h"

static std::vector<GLFWwindow*> DSE {};

static void keyboard_callback(GLFWwindow* window, int key, int, int action, int)
{
  if(key == GLFW_KEY_ESCAPE && action == GLFW_PRESS)
  {
    glfwSetWindowShouldClose(window, GLFW_TRUE);

    auto it = std::find_if( DSE.begin(), DSE.end(), [&window](const auto& cW){ return cW == window; });
    if(it != DSE.end())
    {
	  DSE.erase(it);
      glfwDestroyWindow(window);
      std::cout << "one closed\n";
    }
  }
}


int main(int, char**)
{
  if (!glfwInit()) return EXIT_FAILURE;
  
  DSE.push_back(glfwCreateWindow( 640, 480, "GLFWPP N_1", NULL, NULL ));
  glfwSetKeyCallback(DSE.back(), keyboard_callback);

  DSE.push_back(glfwCreateWindow( 640, 480, "GLFWPP N_2", NULL, NULL ));
  glfwSetKeyCallback(DSE.back(), keyboard_callback);

  DSE.push_back(glfwCreateWindow( 640, 480, "GLFWPP N_3", NULL, NULL ));
  glfwSetKeyCallback(DSE.back(), keyboard_callback);

  while (!DSE.empty())
  {
    for(auto& W: DSE)
    {
      // smb doing...
    }
    glfwPollEvents();
  }
  glfwTerminate();
  return EXIT_SUCCESS;
}
```
work fine.

If use you cpp lib:
```cpp
#include <iostream>
#include <vector>
#include "include/glfwpp/glfwpp.h"

static std::vector<glfw::Window> DSE {};

static void keyboard_callback(glfw::Window& W, glfw::KeyCode K, int, glfw::KeyState S, glfw::ModifierKeyBit)
{
  if(K == glfw::KeyCode::Escape && S == glfw::KeyState::Release)
  { 
    W.setShouldClose(true);
    auto it = std::find_if(DSE.begin(), DSE.end(), [&W](const auto& cW){ return cW == W; });
    if(it != DSE.end())
    {
      DSE.erase(it); // glfwDestroyWindow(W) auto call here
      std::cout << "one closed\n";
    }
  }
}

int main(int, char**)
{
  [[maybe_unused]]auto GLFW = glfw::init();

  DSE.emplace_back( 640, 480, "GLFWPP N_1" );
  DSE.back().keyEvent.setCallback(keyboard_callback);

  DSE.emplace_back( 640, 480, "GLFWPP N_2" );
  DSE.back().keyEvent.setCallback(keyboard_callback);

  DSE.emplace_back( 640, 480, "GLFWPP N_3" );
  DSE.back().keyEvent.setCallback(keyboard_callback);

  while (!DSE.empty())
  {
    for(auto& W: DSE)
    {
     // smb doing...
    }
    glfw::pollEvents();
  }
}
```
work bad - closed only last window. 

For testing you can use my CMakeLists.txt :
```cmake
#
#  cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 ../
#

cmake_minimum_required( VERSION "3.15" )
SET( CMAKE_VERBOSE_MAKEFILE OFF )

if("${CMAKE_SOURCE_DIR}" STREQUAL "${CMAKE_BINARY_DIR}")
  message(FATAL_ERROR "\nPREVENTED IN-TREE BUILD: please, create the build directory outside of the source code and call cmake from there!")
endif()

# using Clang
SET( CLANG TRUE )
SET( CMAKE_C_COMPILER clang CACHE STRING "clang compiler" FORCE )
SET( CMAKE_CXX_COMPILER clang++ CACHE STRING "clang++ compiler" FORCE )
SET( CMAKE_AR      llvm-ar )
SET( CMAKE_LINKER  llvm-ld )
SET( CMAKE_NM      llvm-nm )
SET( CMAKE_OBJDUMP llvm-objdump )
SET( CMAKE_RANLIB  llvm-ranlib )

SET( CMAKE_BUILD_TYPE "Debug" )
OPTION( WITH_DEBUG_MODE "Option debug mode" ON )

project( APP )
include( ExternalProject )

include_directories( "${APP_SOURCE_DIR}/include" )
link_directories ( "${CMAKE_BINARY_DIR}/lib" )

SET( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++2a -fexceptions -Werror" )

# Get glfw
list( APPEND GLFW_CMAKE_ARGS "-DGLFW_BUILD_DOCS=OFF" )
list( APPEND GLFW_CMAKE_ARGS "-DGLFW_BUILD_TESTS=OFF" )
list( APPEND GLFW_CMAKE_ARGS "-DGLFW_BUILD_EXAMPLES=OFF" )
list( APPEND GLFW_CMAKE_ARGS "-DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}" )
list( APPEND GLFW_CMAKE_ARGS "-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}" )
ExternalProject_Add( GLFW
  SOURCE_DIR "d:/dev/cpp/glfw"
  CMAKE_ARGS ${GLFW_CMAKE_ARGS} )

FILE( GLOB APP_SOURCE_FILES "${APP_SOURCE_DIR}/*.cpp" )
add_executable( app ${APP_SOURCE_FILES} )
add_dependencies( app GLFW )
target_link_libraries( app glfw3 )
```

**Comment by janekb04** [comment] 2021-11-15 07:37
@bigov Both examples work for me. Could you verify that you checked out the new `multiple-windows-fix` branch?

**Comment by bigov** [comment] 2021-11-15 08:00
Strange, I can't compile this branch (windows10, msys2 - mingw64 - clang64 -ninja):

```bash
In file included from D:\dev\cpp\muti-win-cpp\main.cpp:7:
In file included from D:\dev\cpp\muti-win-cpp/include/glfwpp/glfwpp.h:13:
D:\dev\cpp\muti-win-cpp/include/glfwpp/window.h:193:20: error: no matching constructor for initialization of
      'glfw::Cursor'
            return Cursor{glfwCreateCursor(&image_, xHot_, yHot_)};
                   ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
D:\dev\cpp\muti-win-cpp/include/glfwpp/window.h:172:11: note: candidate constructor (the implicit copy constructor) not
      viable: cannot convert argument of incomplete type 'GLFWcursor *' to 'const glfw::Cursor' for 1st argument
    class Cursor : public detail::OwningPtr<GLFWcursor>
```

But if you say the example works, then fine. Let's close the issue.

**Comment by janekb04** [comment] 2021-11-15 08:05
Let's not close until we make sure that the code compiles and works correctly.

The code gets successfully compiled [on the CI server](https://github.com/janekb04/glfwpp/actions/runs/1459729901). I will try different compilers on my machine and see if I have any problems with the `Cursor` class.

**Comment by bigov** [comment] 2021-11-15 08:06
ok

**Comment by janekb04** [comment] 2021-11-15 08:08
What's your `clang --version`?

**Comment by bigov** [comment] 2021-11-15 08:21
I don't think that's the problem. This is probably because I only cloned one branch. A little later, I'll try to grab the entire repository and switch the branch before compiling.
```
>clang --version
clang version 13.0.0
Target: x86_64-w64-windows-gnu
Thread model: posix
```

**Comment by janekb04** [comment] 2021-11-15 08:43
I think it's not just your compiler. I tried to compile the code [on godbolt](https://godbolt.org/z/vj8jssaxa) and it fails. 

I pushed a possible fix to branch `multiple-windows-fix`.

**Comment by bigov** [comment] 2021-11-15 10:42
Everything works without errors. Fast and nice job, thanks! May close this issue.

**Comment by janekb04** [comment] 2021-11-15 10:59
Great! Closing and merging right now.

**Closed** 2021-11-15 11:00 UTC
Labels: bug, fix-pending
